services:
  angular-app:
    build: ..
    ports:
      - 4200:80
    volumes:
      - type: bind
        source: ./apache/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
      - type: bind
        source: ../angular-app/target/dist/oauth-demo/
        target: /usr/local/apache2/htdocs/

  spring-app:
    image: spring-oauth-app
#    environment:
#      - SERVER_MAXHTTPHEADERSIZE=10MB
    ports:
      - 8080:8080

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 9090:8080
    volumes:
      - type: bind
        source: ./keycloak/oauth-demo-realm-realm.json
        target: /opt/keycloak/data/import/oauth-demo-realm-realm.json
        # Imports the realm "oauth-demo-realm" with a user "alice" and password "test"
    command:
      - start-dev --import-realm
