spring:
  application:
    name: spring-app-oauth
  session:
    store-type: none #disable sessions
  mvc:
    throw-exception-if-no-handler-found: "true"
    servlet:
      load-on-startup: 1
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:9090/realms/oauth-demo-realm

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG